[font]
size = 15

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[window]
opacity = 1
blur = true
decorations = "none"
startup_mode = "Maximized"

[general]
import = [
    "~/.config/alacritty/theme.toml"
]

[terminal]
