[font]
size = 12.0

[font.normal]
# family = "SauceCodeProNerdFont"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
opacity = 0.8
blur = true
decorations = "none"
startup_mode = "Maximized"

[general]
import = [
    "~/.config/alacritty/theme.toml"
]

[terminal]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
